apiVersion: apps/v1
kind: Deployment
metadata:
  name: pasal-products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pasal-products
  template:
    metadata:
      labels:
        app: pasal-products
    spec:
      containers:
        - name: pasal-products
          image: bharatrose1/pasal-products
          env:
            - name: MONGO_URI
              value: 'mongodb://pasal-products-mongo-srv:27017/products'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBIT_MQ_URL
              value: 'amqp://rabbitmq-srv:5672'
---
apiVersion: v1
kind: Service 
metadata:
  name: pasal-products-srv
spec:
  selector:
    app: pasal-products
  ports:
    - name: pasal-products
      protocol: TCP
      port: 3000
      targetPort: 3000