name: tests-pasal-auth

on:
  pull_request:
    paths:
      - 'pasal-auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd pasal-auth && npm install && npm run test:ci