name: tests-pasal-products

on:
  pull_request:
    paths:
      - 'pasal-products/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd pasal-products && npm install && npm run test:ci